services:
  - type: web
    name: appiapalan-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python seed_system.py && gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        value: postgresql+psycopg://postgres.rjpkyzbvmsooidkckriq:FM1oxFIVN9Up0NZy@aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: POSTGRES_URL
        value: postgresql+psycopg://postgres.rjpkyzbvmsooidkckriq:FM1oxFIVN9Up0NZy@aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: DATABASE_URL
        value: postgresql+psycopg://postgres.rjpkyzbvmsooidkckriq:FM1oxFIVN9Up0NZy@aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        value: https://rjpkyzbvmsooidkckriq.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcGt5emJ2bXNvb2lka2NrcmlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0ODE3NjksImV4cCI6MjA4NzA1Nzc2OX0.BTsVAlFnwElAuxwBdNOPmXFN2H_6t4C4XJeuV6wMWJQ
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcGt5emJ2bXNvb2lka2NrcmlxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTQ4MTc2OSwiZXhwIjoyMDg3MDU3NzY5fQ.R2Ldf4lvxFrIvdr72qTz0PH6LzxqkXysmFJeGjkwpfc
      - key: SUPABASE_JWT_SECRET
        value: JakVWsnmgaK9KErSUvkZnq+Nb5PJGHPbzoA0HsAjmRmQrKOZl4XsFul8tuXc+buB17iowjWUrOBByBFM4mjMFg==
      - key: AI_SERVICE_URL
        value: http://localhost:8001/v1/predict
